teknoparrot["Jurassic Park.squashfs"].emulator=linuxloader-dcg
teknoparrot["Jurassic Park.squashfs"].core=linuxloader-dcg-dcg
teknoparrot["Galaga Assault.squashfs"].emulator=linuxloader-dcg
teknoparrot["Galaga Assault.squashfs"].core=linuxloader-dcg
teknoparrot["Cruis'n Blast.squashfs"].emulator=linuxloader-dcg
teknoparrot["Cruis'n Blast.squashfs"].core=linuxloader-dcg
teknoparrot["Pac-Man Chomp Mania.squashfs"].core=linuxloader-dcg
teknoparrot["Pac-Man Chomp Mania.squashfs"].emulator=linuxloader-dcg
teknoparrot["Terminator Salvation.squashfs"].core=linuxloader-dcg
teknoparrot["Terminator Salvation.squashfs"].emulator=linuxloader-dcg
teknoparrot["Big Buck World.squashfs"].core=linuxloader-dcg
teknoparrot["Big Buck World.squashfs"].emulator=linuxloader-dcg
teknoparrot["The Walking Dead.squashfs"].core=linuxloader-dcg
teknoparrot["The Walking Dead.squashfs"].emulator=linuxloader-dcg
teknoparrot["Halo Fireteam Raven.squashfs"].core=linuxloader-dcg
teknoparrot["Halo Fireteam Raven.squashfs"].emulator=linuxloader-dcg
teknoparrot["Pink Panther Jewel Heist.squashfs"].core=linuxloader-dcg
teknoparrot["Pink Panther Jewel Heist.squashfs"].emulator=linuxloader-dcg
teknoparrot["Aliens Armageddon.squashfs"].core=linuxloader-dcg
teknoparrot["Aliens Armageddon.squashfs"].emulator=linuxloader-dcg
teknoparrot["Big Buck HD Wild.squashfs"].core=linuxloader-dcg
teknoparrot["Big Buck HD Wild.squashfs"].emulator=linuxloader-dcg
teknoparrot.use_guns=1
teknoparrot.emulator=wine
teknoparrot.wine-runner=wine-proton
teknoparrot.bezel=none
teknoparrot.dxvk=1
teknoparrot.esync=1